# Generated by Django 2.2.12 on 2020-04-22 04:38

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('growvick', 'User')
    User(name="Joe Silver", email="joe@email.com", document="22342342", phone="00000000").save()

class Migration(migrations.Migration):

    dependencies = [
        ('growvick', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
